import { defaultSchema } from "rehype-sanitize";

export const customSchema: typeof defaultSchema = {
  ...defaultSchema,
  attributes: {
    ...defaultSchema.attributes,
    "*": [
      ...(defaultSchema.attributes?.["*"] || []),
      "class",
      "className",
      "style",
      "id",
    ],
    span: ["class", "className", "style", "aria-hidden", "role"],
    div: ["class", "className", "style"],
    math: ["xmlns", "display", "class"],
    semantics: ["class"],
    mrow: ["class"],
    mi: ["mathvariant", "class"],
    mn: ["class"],
    mo: ["stretchy", "fence", "separator", "lspace", "rspace", "class"],
    mtext: ["class"],
    mspace: ["width", "class"],
    msup: ["class"],
    msub: ["class"],
    msubsup: ["class"],
    mfrac: ["linethickness", "class"],
    msqrt: ["class"],
    mroot: ["class"],
    munderover: ["class"],
    munder: ["class"],
    mover: ["class"],
    annotation: ["encoding"],
    svg: [
      "xmlns",
      "width",
      "height",
      "viewBox",
      "class",
      "style",
      "preserveAspectRatio",
    ],
    path: ["d", "fill", "stroke", "strokeWidth", "class"],
    g: ["class", "transform"],
    use: ["href", "xlinkHref", "class"],
  },
  tagNames: [
    ...(defaultSchema.tagNames || []),
    "math",
    "semantics",
    "mrow",
    "mi",
    "mn",
    "mo",
    "mtext",
    "mspace",
    "msup",
    "msub",
    "msubsup",
    "mfrac",
    "msqrt",
    "mroot",
    "munderover",
    "munder",
    "mover",
    "annotation",
    "mtable",
    "mtr",
    "mtd",
    "svg",
    "path",
    "g",
    "use",
    "symbol",
    "defs",
    "line",
    "rect",
    "circle",
    "ellipse",
    "polygon",
    "polyline",
  ],
};
